# Generated by Django 5.2.7 on 2026-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWorkerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('work_location', models.CharField(help_text='Primary work area or reporting location.', max_length=500)),
                ('available_days', models.CharField(help_text='Days you are typically available (e.g. Mon–Fri).', max_length=200)),
                ('available_hours', models.CharField(help_text='Hours (e.g. 8:00 AM – 4:00 PM).', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(help_text='Sensor or asset ID (unique).', max_length=64, unique=True)),
                ('location_description', models.CharField(max_length=500)),
                ('cleaning_priority', models.PositiveSmallIntegerField(default=1, help_text='Higher number = higher priority to clean next.')),
                ('debris_level_percent', models.PositiveSmallIntegerField(blank=True, help_text='Estimated fullness / debris from sensor (0–100).', null=True)),
                ('sensor_water_level_cm', models.PositiveSmallIntegerField(blank=True, help_text='Optional water depth reading (cm).', null=True)),
                ('needs_cleaning', models.BooleanField(default=True)),
                ('last_sensor_read_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cleaning_priority', '-needs_cleaning', 'site_code'],
            },
        ),
        migrations.CreateModel(
            name='HomeownerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
